CREATE TABLE IF NOT EXISTS "users" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "username" VARCHAR(255),
    "role" VARCHAR(255),
    "password" VARCHAR(255),
    "created_at" TIMESTAMP,
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "project" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "client_id" INTEGER,
    "contractor_id" INTEGER,
    "title" VARCHAR(255) NOT NULL,
    "description" TEXT,
    "budget" INTEGER,
    "updated_at" TIMESTAMP,
    "status" VARCHAR(255),
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "bids" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "project_id" INTEGER,
    "contractor_id" INTEGER,
    "price" INTEGER NOT NULL,
    "message" TEXT,
    "status" VARCHAR(255),
    "updated_at" TIMESTAMP,
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "deliverables" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "project_id" INTEGER,
    "file_name" VARCHAR(255) NOT NULL,
    "file_path" VARCHAR(255),
    "message" TEXT,
    "uploaded_at" TIMESTAMP,
    PRIMARY KEY("id")
);

-- 議題 (Issues) 表格
CREATE TABLE IF NOT EXISTS "issues" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "project_id" INTEGER,
    "creator_id" INTEGER,
    "title" VARCHAR(255) NOT NULL,
    "status" VARCHAR(50) DEFAULT 'open',
    "created_at" TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY("id")
);

-- 議題留言 (Issue Comments) 表格
CREATE TABLE IF NOT EXISTS "issue_comments" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "issue_id" INTEGER,
    "user_id" INTEGER,
    "message" TEXT NOT NULL,
    "created_at" TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY("id")
);

-- 評價 (Reviews) 表格
CREATE TABLE IF NOT EXISTS "reviews" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "project_id" INTEGER,
    "reviewer_id" INTEGER, 
    "target_id" INTEGER,    
    "dim1" INTEGER,         
    "dim2" INTEGER,        
    "dim3" INTEGER,        
    "comment" TEXT,         
    "created_at" TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY("id")
);

-- 原有的關聯設定
ALTER TABLE "project"
ADD FOREIGN KEY("client_id") REFERENCES "users"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "project"
ADD FOREIGN KEY("contractor_id") REFERENCES "users"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "bids"
ADD FOREIGN KEY("project_id") REFERENCES "project"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "bids"
ADD FOREIGN KEY("contractor_id") REFERENCES "users"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "deliverables"
ADD FOREIGN KEY("project_id") REFERENCES "project"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- 議題相關的關聯設定
ALTER TABLE "issues"
ADD FOREIGN KEY("project_id") REFERENCES "project"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "issues"
ADD FOREIGN KEY("creator_id") REFERENCES "users"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "issue_comments"
ADD FOREIGN KEY("issue_id") REFERENCES "issues"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "issue_comments"
ADD FOREIGN KEY("user_id") REFERENCES "users"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- 新增：評價相關的關聯設定
ALTER TABLE "reviews"
ADD FOREIGN KEY("project_id") REFERENCES "project"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "reviews"
ADD FOREIGN KEY("reviewer_id") REFERENCES "users"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "reviews"
ADD FOREIGN KEY("target_id") REFERENCES "users"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;